### ISSUE TITLE
Missing API functionality of MemberMacro?

### ISSUE THREAD

**Issue by miku1958** [DougGregor/swift-macro-examples#11]
Hi I am learning MemberMacro , I don't know why _storage is defined in here
https://github.com/DougGregor/swift-macro-examples/blob/9548af5ae7a71435b78d8697467601b2edfaa1ad/MacroExamplesLib/Macros.swift#L47

but DictionaryIndirectionMacro.swift use string constants:
https://github.com/DougGregor/swift-macro-examples/blob/9548af5ae7a71435b78d8697467601b2edfaa1ad/MacroExamplesPlugin/DictionaryIndirectionMacro.swift#L57

I also don't find "_storage" in AttributeSyntax or DeclGroupSyntax, is this a missing API function or is "named(_storage)" just not useful?

Thanks!

**Comment by miku1958** [comment]
Forgot to say, I test it with XCTestCase

**Comment by DougGregor** [comment]
The reasons for the `named(_storage)` here are described in the proposal for [attached macros](https://github.com/apple/swift-evolution/pull/1932).
