### ISSUE TITLE
Is @attached mark necessary?

### ISSUE THREAD

**Issue by miku1958** [DougGregor/swift-macro-examples#12]
I remove these two @attached mark 
<img width="684" alt="image" src="https://user-images.githubusercontent.com/24806909/218951964-1b98691e-7613-4204-9b17-5b6e8c68c5ba.png">

But the function of MemberMacro and MemberAttributeMacro will still be called, I thought @attached was something like a switch.

**Comment by miku1958** [comment]
Forgot to say, I test it with XCTestCase

**Comment by DougGregor** [comment]
The compiler requires `@attached` and such; it's not used in the unit tests for macro implementations.

**Comment by miku1958** [comment]
@DougGregor Got it, thanks for the explanation!
