### ISSUE TITLE
Is there a "AttributeMacro"?

### ISSUE THREAD

**Issue by miku1958** [DougGregor/swift-macro-examples#14]
Hi, I was wondering if there is an "AttributeMacro" that I can use to add some custom attributes to a variable. This can work with MemberMacro, I can do this by determining if member has the attribute I marked. 

It will look the same as PropertyWrapper, but with a simpler type structure.

For example, I can use MemberMacro to generate the init(from: ) of Decoable, and do some pre-processing base on different custom attribute from "AttributeMacro"

**Comment by DougGregor** [comment]
We have some concerns with introducing an `AttributeMacro`, but it's certainly something that's come up a few times on the macros discussion on the [Swift forums](https://forums.swift.org/t/a-possible-vision-for-macros-in-swift/60900/121). That's where we should have design discussions.
