### ISSUE TITLE
[MacroExamplesPluginTest] Cannot find type 'MacroSystem' in scope

### ISSUE THREAD

**Issue by davdroman** [DougGregor/swift-macro-examples#2]
The test target fails to build with the following error:

<img width="960" alt="CleanShot 2022-12-29 at 15 38 05@2x" src="https://user-images.githubusercontent.com/2538074/209975935-0b9adc54-aec2-4acc-9e1d-a93453d49369.png">

Attempted on a MacBook Pro M1 running macOS 13.1 and Xcode 14.2. Swift dev snapshot dated 2022-12-21.

**Comment by DougGregor** [comment]
`MacroSystem` went away; I've updated for the simplified API.
