### ISSUE TITLE
How does the macro feature not use SPM integration?

### ISSUE THREAD

**Issue by 0x1306a94** [DougGregor/swift-macro-examples#36]
I observed that when using SPM integration, the macro plugin is loaded via `-load-plugin-library xx/Debug/MacroExamplesPlugin#MacroExamplesPlugin` in the compile command.

Then I made `MacroExamplesLib` into `xcframework` and integrated it into the project, and configured `OTHER_SWIFT_FLAGS=-load-plugin-executable xx/Debug/MacroExamplesPlugin#MacroExamplesPlugin` to compile and report an error and prompt `External macro implementation type 'MacroExamplesPlugin.StringifyMacro' could not be found for macro 'stringify'; the type must be public and provided via '-load-plugin-library'`

**Comment by 0x1306a94** [comment]
Problem solved

```bash
OTHER_SWIFT_FLAGS=-Xfrontend -load-plugin-executable -Xfrontend xx/Debug/MacroExamplesPlugin#MacroExamplesPlugin
```

**Comment by DougGregor** [comment]
This project's build setup predates the availability of SwiftPM integration in Xcode, which is why it uses "Other Swift Flags" everywhere to achieve a similar effect. At this point, we could switch to using SwiftPM.
