### ISSUE TITLE
Issue with '@attached(conformance)'  rule

### ISSUE THREAD

**Issue by AntonShapoval** [DougGregor/swift-macro-examples#40]
Hi @DougGregor, I've issue with '@attached(conformance)'  rule.
Xcode suggests: 'Conformance macros are replaced by extension macros'. When I change 'conformance' for 'extension', error 'Conformance to 'OptionSet' is not covered by macro 'OptionSet'' is appeared.

Xcode version: 15.0 beta 6
Package: "https://github.com/apple/swift-syntax.git", tag: "509.0.0-swift-DEVELOPMENT-SNAPSHOT-2023-08-07-a"

<img width="946" alt="Screenshot 2023-08-12 at 8 54 31 AM" src="https://github.com/DougGregor/swift-macro-examples/assets/18569321/fd366e7f-2f6f-4d5b-aef3-4ba811c620d5">
<img width="936" alt="Screenshot 2023-08-12 at 9 07 06 AM" src="https://github.com/DougGregor/swift-macro-examples/assets/18569321/64ede547-c446-47d8-9c98-ef49af31e0a2">

**Comment by akashgurava** [comment]
Im getting `Cannot find type 'ExtensionMacro' in scope` when trying to implement a extension macro :(

**Comment by akashgurava** [comment]
Changing the version to `"509.0.0-swift-5.9-DEVELOPMENT-SNAPSHOT-2023-08-12-a"` in package.swift worked. Also there seems to be a minimal [example](https://github.com/hborla/swift-syntax/blob/cf1e15b39939b50576344ee7e8e80bbd5315f4f0/Examples/Sources/ExamplePlugin/Macros.swift)

**Comment by AntonShapoval** [comment]
@akashgurava thanks for reply, I've setup this version of package, but 'Conformance macros are replaced by extension macros' still exists.

**Comment by akashgurava** [comment]
you should change your code to `@attached(extenstion, conformances: YourProtocol)` and your macro should conform to ExtensionProtocol. You can refer to https://github.com/apple/swift-evolution/blob/main/proposals/0402-extension-macros.md

**Comment by akashgurava** [comment]
Something like this for te macro declaration.
```swift
@attached(extension, conformances: Table)
public macro Arkiv() = #externalMacro(module: "ArkivMacros", type: "ArkivMacro")
```
Something like this for the macro.
```swift
public struct ArkivMacro: ExtensionMacro {
    public static func expansion(of node: SwiftSyntax.AttributeSyntax, attachedTo declaration: some SwiftSyntax.DeclGroupSyntax, providingExtensionsOf type: some SwiftSyntax.TypeSyntaxProtocol, conformingTo protocols: [SwiftSyntax.TypeSyntax], in context: some SwiftSyntaxMacros.MacroExpansionContext) throws -> [SwiftSyntax.ExtensionDeclSyntax] {
        let sendableExtension: DeclSyntax =
            """
            extension \(type.trimmed): Table {}
            """

        guard let extensionDecl = sendableExtension.as(ExtensionDeclSyntax.self) else {
            return []
        }

        return [extensionDecl]
    }
}
```

**Comment by AntonShapoval** [comment]
Yes, it works, @akashgurava thanks a lot!

<img width="744" alt="Screenshot 2023-08-16 at 4 25 09 PM" src="https://github.com/DougGregor/swift-macro-examples/assets/18569321/fefadebc-45d0-43f0-8d05-ee1df4983d14">
